[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=../vault/id_ed25519
master_name=k8s-master-01
master_ip=192.168.10.20

[masters]
k8s-master-01 ansible_host=192.168.10.20
k8s-master-02 ansible_host=192.168.20.34
k8s-master-03 ansible_host=192.168.10.28

    
[workers] 
k8s-worker-01 ansible_host=192.168.10.8
k8s-worker-02 ansible_host=192.168.20.4
k8s-worker-03 ansible_host=192.168.10.15


[nat_gateway]
nat ansible_host=192.168.1.254


[admin]
admin ansible_host=192.168.10.21


[all:children]
masters
workers
nat_gateway
admin