[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=../vault/id_ed25519
master_name=k8s-master-01
master_ip=192.168.10.17

[masters]
k8s-master-01 ansible_host=192.168.10.17
k8s-master-02 ansible_host=192.168.20.31
k8s-master-03 ansible_host=192.168.10.28

    
[workers] 
k8s-worker-01 ansible_host=192.168.10.33
k8s-worker-02 ansible_host=192.168.20.19
k8s-worker-03 ansible_host=192.168.10.9


[nat_gateway]
nat ansible_host=192.168.1.254


[admin]
admin ansible_host=192.168.10.21


[all:children]
masters
workers
nat_gateway
admin